services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.3-fpm
    container_name: php-fpm
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    image: mariadb
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: messenger_fake
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
